module Localizable
  extend ActiveSupport::Concern

  included do
    before_action :set_locale
  end

  private

  def set_locale
    I18n.locale = extract_locale || I18n.default_locale
    session[:locale] = I18n.locale
  end

  def extract_locale
    # Order of priority:
    # 1. URL parameter (?locale=ne)
    # 2. Session value
    # 3. User preference (once User model exists)
    parsed_locale = params[:locale] || session[:locale] || (current_user&.preferred_locale if defined?(current_user))
    
    # Mitigate tampering (T-01-01-01) by validating against available locales
    if I18n.available_locales.map(&:to_s).include?(parsed_locale.to_s)
      parsed_locale
    else
      nil
    end
  end

  # Keep the locale in URLs generated by url_for
  def default_url_options
    { locale: I18n.locale }
  end
end
